Repository cloudposse/terraform-provider-context, pull requests merged in 2024-04, with the labels that each got.

#14 fix bug with regex validation
  internal/model/property.go
Labels: patch

#15 fix bug with empty strings in labels
  go.mod
  go.sum
  internal/model/provider_config.go
Labels: minor, no-release

#16 fix bug with tag being rendered with "" value
  internal/model/provider_config.go
  internal/provider/tags_data_source_test.go
Labels: do not merge, minor

#17 Go auto release workflows
  .github/auto-release.yml
  .github/workflows/auto-release.yml
  .github/workflows/build-assets.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .goreleaser.yml
Labels: ready-for-review
